user_homepage:
    path:    /
    defaults: { _controller: PicoUserBundle:User:home }

user_show:
    path: /show-profile/{username}
    defaults: { _controller : PicoUserBundle:User:show, username: null }

user_find:
    path: /user-find/
    defaults: { _controller: PicoUserBundle:User:find }

user_edit:
    path: /user-edit/
    defaults: { _controller: PicoUserBundle:Profile:edit }

user_register:
    path: /user-register/
    defaults: { _controller: PicoUserBundle:Registration:register }

user_update_profile_picture:
    path: /user/profile-picture/
    defaults: { _controller: PicoUserBundle:ProfilePicture:update }