user_homepage:
    path:    /
    defaults: { _controller: PicoUserBundle:User:home }


user_show:
    path:    /show-profile
    defaults: { _controller: PicoUserBundle:User:show }


user_edit:
    path: /user-edit/
    defaults: { _controller: PicoUserBundle:Profile:edit }

user_register:
    path: /user-register/
    defaults: { _controller: PicoUserBundle:Registration:register }