services:
    pico_user.registration.form.type:
        class: Pico\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: pico_user_registration }
    pico_user.profile.form.type:
        class: Pico\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: pico_user_profile }
