pico_messagerie:
    resource: "@PicoMessageBundle/Resources/config/routing.yml"
    prefix:   /mp/

pico_user:
    resource: "@PicoUserBundle/Resources/config/routing.yml"
    prefix:   /

pico_league:
    resource: "@PicoLeagueBundle/Resources/config/routing.yml"
    prefix:   /league/

pico_notification:
    resource: "@PicoNotificationBundle/Resources/config/routing.yml"
    prefix:   /notif/

pico_assets:
    resource: "@PicoAssetsBundle/Resources/config/routing.yml"
    prefix:   /assets/

calendar_manager:
    resource: "@CalendarManagerBundle/Resources/config/routing.yml"
    prefix:   /oki/
    options:
        expose: true

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

adesigns_calendar:
    resource: "@ADesignsCalendarBundle/Resources/config/routing.xml" 

# FIREWALL


fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile/change-password


# /FIREWALL
