user_management:
    resource: "@UserManagementBundle/Resources/config/routing.yml"
    prefix:   /

pico_library_assets:
    resource: "@PicoLibraryAssetsBundle/Resources/config/routing.yml"
    prefix:   /

