user_management:
    resource: "@UserManagementBundle/Resources/config/routing.yml"
    prefix:   /

pico_assets:
    resource: "@PicoAssetsBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

adesigns_calendar:
    resource: "@ADesignsCalendarBundle/Resources/config/routing.xml" 