Rest_User : 
  type : rest
  resource: "@PicoUserBundle/Resources/config/routing_rest.yml"

users : 
  type: rest
  resource:     "@PicoUserBundle/Controller/UserRestController.php"
  name_prefix:  api_