security:
    encoders:
        Pico\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_USER:       ROLE_USER
        ROLE_MODERATEUR: [ROLE_USER]
        ROLE_LIGUE_CREATEUR: [ROLE_MODERATEUR]
        ROLE_ADMIN: [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]

    providers:
        user_provider:
            id: fos_user.user_provider.username_email

    firewalls:
        main_firewall:
            pattern: ^/
            anonymous: true
            provider:  user_provider
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path: fos_user_security_logout
                target: /
            remember_me:
                key: %secret%

    # URL SECURITY
    access_control:

        # LOGIN
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: http }

        # LOGOUT
        - { path: ^/logout, roles: IS_AUTHENTICATED_REMEMBERED, requires_channel: http }

        # AFFICHAGE DE LA VUE PROFIL UTILISATEUR
        - { path: ^/profil, roles: ROLE_USER }

        # AFFICHAGE DE LA VUE DE GESTION DE LIGUE (Leo mets le path qui te plait)
        - { path: ^/ligues/gestion, roles: ROLE_MODERATEUR }

        # AFFICHAGE DE LA PARTIE ADMIN (useless)
        - { path: ^/admin, roles: ROLE_ADMIN }