security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: toto, roles: [ 'ROLE_USER' ] }
                    admin: { password: root, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        main_firewall:
            pattern: ^/
            anonymous: true
            provider:  in_memory
            form_login:
                login_path: user_form_login
                check_path: user_form_login_check
            logout:
                path: user_logout
                target: /

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }