<?php

namespace Pico\CalendarManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClubeventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClubeventRepository extends EntityRepository
{
}
