pico_league_affichage:
    path:     /affichage/{Type}/{Id}/{InfoSupp}
    defaults: { _controller: PicoLeagueBundle:League:index,Type: false, Id: false, InfoSupp: false}
    requirements:
        Id:  \d+
        Type: Ligues|Clubs|Equipes

pico_league_affichage_ajax:
    path:     /ajax/affichage/{Type}
    defaults: { _controller: PicoLeagueBundle:League:getAffichage }

subscribe_to_equipe:
    path:    /ajax/subscribeEquipe/{Id}
    defaults: { _controller: PicoLeagueBundle:League:subscribeToEquipe}
    requirements:
        Id:  \d+

gestion_equipe:
    path:    /ajax/gestion-equipe/{Id}
    defaults: { _controller: PicoLeagueBundle:League:gestionEquipe}
