pico_league_affichage:
    path:     /affichage/{Type}/{Id}
    defaults: { _controller: PicoLeagueBundle:League:index,Type: false, Id: false}
    requirements:
        Id:  \d+
        Type: Leagues|Clubs|Equipes

pico_league_affichage_ajax:
    path:     /ajax/affichage/{Type}
    defaults: { _controller: PicoLeagueBundle:League:getAffichage }
