pico_league_affichage:
    path:     /affichage/{Type}/{Id}/{InfoSupp}
    defaults: { _controller: PicoLeagueBundle:League:index,Type: false, Id: false, InfoSupp: false}
    requirements:
        Id:  \d+
        Type: Ligues|Clubs|Equipes

pico_league_create_league:
    path: /create
    defaults: { _controller: PicoLeagueBundle:League:create }

pico_league_affichage_ajax:
    path:     /ajax/affichage/{Type}
    defaults: { _controller: PicoLeagueBundle:League:getAffichage }
    options:
        expose: true
        
subscribe_to_equipe:
    path:    /ajax/subscribeEquipe/{Id}
    defaults: { _controller: PicoLeagueBundle:League:subscribeToEquipe}
    requirements:
        Id:  \d+

gestion_equipe:
    path:    /ajax/gestion-equipe/{Id}
    defaults: { _controller: PicoLeagueBundle:League:gestionEquipe}
    options:
        expose: true
        
pico_league_get_form:
    path:    /ajax/form/{Type}/{Id}/{IdCible}
    defaults: { _controller: PicoLeagueBundle:League:manageForm,Id: false, IdCible: false}
    requirements:
        Id:  \d+
        Type: Ligues|Clubs|Equipes
    options:
        expose: true

delete:
    path:    /ajax/delete/{Type}/{Id}
    defaults: { _controller: PicoLeagueBundle:League:delete}
    requirements:
        Id:  \d+
        Type: Ligues|Clubs|Equipes
    options:
        expose: true


# SPORT

pico_league_create_sport:
    path: /sport/create
    defaults: { _controller: PicoLeagueBundle:Sport:create }