Pico\CalendarManagerBundle\Entity\Groupevent:
    type: entity
    table: null
    repositoryClass: Pico\CalendarManagerBundle\Entity\GroupeventRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        event:
            type: integer
            column: Event
        equipe:
            type: integer
            column: Equipe
    lifecycleCallbacks: {  }
