pico_news_show:
    path:     /show
    defaults: { _controller: PicoNewsBundle:Article:show }
    
pico_news_show_detail:
    path: /show/{idNews}
    defaults: { _controller: PicoNewsBundle:Article:showDetail }
    requirements:
        Id:  \d+
    
pico_news_create:
    path:     /create
    defaults: { _controller: PicoNewsBundle:Article:create }

pico_news_delete:
    path: /delete
    defaults: { _controller: PicoNewsBundle:Article:delete }

pico_news_show_image:
    path:    /showimage/{ArticleId}
    defaults: { _controller: PicoNewsBundle:NewsImages:showImage}

pico_news_uodate_image:
    path:    /updateImage/{ArticleId}
    defaults: { _controller: PicoNewsBundle:NewsImages:XXXXXXX}