<?php

namespace Pico\NewsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewsImagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsImagesRepository extends EntityRepository
{
}
