<?php

namespace Pico\LeagueBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserToEquipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserToEquipeRepository extends EntityRepository
{
}
